### ISSUE TITLE
Add Open Graph + Twitter Card tags

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfrica/academy.AFRICA-ARCHIVED#4]
## Description
Currently the academy.AFRICA website doesn't share socially very well. We should therefore add Open Graph and Twitter tags.

## Screenshots

https://developers.facebook.com/tools/debug/sharing/?q=academy.africa

## To Reproduce

https://developers.facebook.com/tools/debug/sharing/?q=academy.africa

## Tasks

- [ ] Create images to be used
- [ ] Add open graph tags
- [ ] Add twitter card tags
- [ ] Test extensively
